version: 2
updates:
  - package-ecosystem: bazel
    directory: /
    schedule:
      interval: "weekly"
  - package-ecosystem: gomod
    directory: /go
    schedule:
      interval: "weekly"
  - package-ecosystem: pip
    directory: /python
    schedule:
      interval: "weekly"
